import { Balsamiq_Sans } from "next/font/google";
import { Footer, Header } from "@/components";
import "./globals.css";

const balsamiq = Balsamiq_Sans({
   subsets: ["cyrillic"],
   weight: "400",
  });

export const metadata = {
  title: "Fat burgers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={balsamiq.className}>
        <div className="content">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
